# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{acts_as_sanitiled}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Gabe da Silveira"]
  s.date = %q{2009-10-14}
  s.description = %q{A modernized version of Chris Wansthrath's venerable acts_as_textiled. It automatically textiles and then sanitizes columns to your specification.  Ryan Grove's excellent Sanitize gem with nokogiri provides the backend for speedy and robust filtering of your output in order to: restrict Textile to a subset of HTML, guarantee well-formedness, and of course prevent XSS.}
  s.email = %q{gabe@websaviour.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    "CHANGELOG",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/acts_as_sanitiled.rb",
     "rails/init.rb",
     "spec/sanitiled_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/dasil003/acts_as_sanitiled}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Automatically textiles and/or sanitizes ActiveRecord columns}
  s.test_files = [
    "spec/sanitiled_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<nokogiri>, ["~> 1.3.3"])
      s.add_runtime_dependency(%q<sanitize>, ["~> 1.1.0"])
      s.add_runtime_dependency(%q<RedCloth>, [">= 0"])
      s.add_development_dependency(%q<bacon>, [">= 0"])
      s.add_development_dependency(%q<activesupport>, [">= 0"])
    else
      s.add_dependency(%q<nokogiri>, ["~> 1.3.3"])
      s.add_dependency(%q<sanitize>, ["~> 1.1.0"])
      s.add_dependency(%q<RedCloth>, [">= 0"])
      s.add_dependency(%q<bacon>, [">= 0"])
      s.add_dependency(%q<activesupport>, [">= 0"])
    end
  else
    s.add_dependency(%q<nokogiri>, ["~> 1.3.3"])
    s.add_dependency(%q<sanitize>, ["~> 1.1.0"])
    s.add_dependency(%q<RedCloth>, [">= 0"])
    s.add_dependency(%q<bacon>, [">= 0"])
    s.add_dependency(%q<activesupport>, [">= 0"])
  end
end
